export const HEADER_HEIGHT = 57
export const NAV_BAR_HEIGHT_NORMAL = 135
export const NAV_BAR_HEIGHT_COLLAPSED = 80
export const CONTENT_TOP_POSITION_NORMAL = HEADER_HEIGHT + NAV_BAR_HEIGHT_NORMAL
export const CONTENT_HEIGHT_NORMAL = `calc(100% - ${CONTENT_TOP_POSITION_NORMAL}px)`
export const CONTENT_HEIGHT_COLLAPSED = `calc(100% - ${NAV_BAR_HEIGHT_COLLAPSED}px)`
